---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: i3o-controller
  namespace: traefik-mesh
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "i3o.chartLabel" . | quote}}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: i3o-controller-role
  namespace: traefik-mesh
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "i3o.chartLabel" . | quote}}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
  - apiGroups:
      - access.smi-spec.io
      - specs.smi-spec.io
      - split.smi-spec.io
    resources:
      - traffictargets
      - tcproutes
      - httproutegroups
      - trafficsplits
      - events
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: i3o-controller
  namespace: traefik-mesh
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "i3o.chartLabel" . | quote}}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: i3o-controller-role
subjects:
- kind: ServiceAccount
  name: i3o-controller
  namespace: traefik-mesh
