apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: traefik.containo.us
  version: v1alpha1
  scope: Namespaced
  names:
    plural: ingressroutes
    singular: ingressroute
    kind: IngressRoute
    shortNames:
    - ir
