apiVersion: v1
kind: Namespace
metadata:
  name: traefik-mesh
  labels:
    app: {{ .Release.Name | quote }}
    chart: {{ include "i3o.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
