project_name: traefik-mesh

builds:
  - binary: traefik-mesh

    main: ./cmd/mesh/mesh.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/traefik/mesh/pkg/version.Version={{.Version}}
      - -X github.com/traefik/mesh/pkg/version.Commit={{.Commit}}
      - -X github.com/traefik/mesh/pkg/version.Date={{.Date}}
    goos:
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64

archives:
  - id: traefik-mesh
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    files:
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'
