project_name: maesh

builds:
  - binary: maesh

    main: ./cmd/maesh/maesh.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/containous/maesh/cmd/version.version={{.Version}}
      - -X github.com/containous/maesh/cmd/version.commit={{.Commit}}
      - -X github.com/containous/maesh/cmd/version.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
      - 6
      - 5

    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: maesh
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'
