---
apiVersion: v1
kind: Service
metadata:
  name: b
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
  selector:
    app: b

---
apiVersion: v1
kind: Service
metadata:
  name: b-v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
  selector:
    app: b
    version: v1

---
apiVersion: v1
kind: Service
metadata:
  name: b-v2
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
  selector:
    app: b
    version: v2
