apiVersion: v1
kind: Service
metadata:
  name: i3o-mesh-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: mesh-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: mesh-api
  selector:
    component: i3o-mesh
