apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-a
  namespace: test

---
apiVersion: v1
kind: Pod
metadata:
  name: client-a
  namespace: test
spec:
  serviceAccountName: client-a
  containers:
    - name: client-a
      image: giantswarm/tiny-tools:3.9
      command:
        - "sleep"
        - "36000"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-b
  namespace: test

---
apiVersion: v1
kind: Pod
metadata:
  name: client-b
  namespace: test
spec:
  serviceAccountName: client-b
  containers:
    - name: client-b
      image: giantswarm/tiny-tools:3.9
      command:
        - "sleep"
        - "36000"