---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jaeger
  labels:
    app: maesh
    component: jaeger
    chart: {{ include "maesh.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: maesh
      component: jaeger
