---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: jaeger-query
spec:
  ports:
    - name: query-http
      protocol: TCP
      port: 16686
      targetPort: serve-frontend
  selector:
    app: maesh
    component: jaeger
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: jaeger-collector
spec:
  ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: collector-tch
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: collector-http
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: collector-zip
  selector:
    app: maesh
    component: jaeger
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: jaeger-agent
spec:
  ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: thrift-legacy
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: compact-thrift
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: binary-thrift
    - name: agent-configs
      port: 5778
      protocol: TCP
      targetPort: serve-configs
  clusterIP: None
  selector:
    app: maesh
    component: jaeger

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: jaeger-zipkin
spec:
  ports:
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: collector-zip
  clusterIP: None
  selector:
    app: maesh
    component: jaeger
