---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: a
  namespace: test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: b
  namespace: test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c
  namespace: test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: d
  namespace: test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e
  namespace: test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcp
  namespace: test


