---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: a-b
  namespace: test
destination:
  kind: ServiceAccount
  name: b
  namespace: test
specs:
- kind: HTTPRouteGroup
  name: app-routes
  namespace: test
  matches:
  - foo
sources:
- kind: ServiceAccount
  name: a
  namespace: test

#---
#kind: TrafficTarget
#apiVersion: access.smi-spec.io/v1alpha1
#metadata:
#  name: c-b
#destination:
#  kind: ServiceAccount
#  name: b
#  namespace: test
#specs:
#- kind: HTTPRouteGroup
#  name: app-routes
#  matches:
#  - foo
#sources:
#- kind: ServiceAccount
#  name: c
#  namespace: test

---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: c-d
  namespace: test
destination:
  kind: ServiceAccount
  name: d
  namespace: test
specs:
- kind: HTTPRouteGroup
  name: app-routes
  namespace: test
  matches:
  - bar
sources:
- kind: ServiceAccount
  name: c
  namespace: test
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: tcp-access
  namespace: test
destination:
  kind: ServiceAccount
  name: tcp
  namespace: test
specs:
  - kind: TCPRoute
    name: tcp-access
    namespace: test
sources:
  - kind: ServiceAccount
    name: d
    namespace: test
