apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: test
  labels:
    app: server
spec:
  containers:
    - name: server
      image: containous/whoamiudp:v0.0.1
      imagePullPolicy: Always
      ports:
        - name: udp
          protocol: UDP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: test
  labels:
    app: server
    plop: cool
  annotations:
    maesh.containo.us/traffic-type: udp
spec:
  type: ClusterIP
  ports:
    - name: server
      protocol: UDP
      port: 8080
  selector:
    app: server
