
apiVersion: v1
name: i3o
version: 0.0.1
appVersion: 0.0.1
description: A Simple Service Mesh
keywords:
- traefik
- mesh
home: https://containo.us/
maintainers:
- name: emilevauge
  email: emile@vauge.com
- name: dtomcej
  email: daniel@containo.us
- name: mmatur
  email: michael@containo.us
engine: gotpl
icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
