---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: a
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: b
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: d
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e
  namespace: default

