---
apiVersion: v1
kind: Service
metadata:
  name: traefik-mesh-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: controller
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: api
  selector:
    app: maesh
    component: controller
    release: {{ .Release.Name | quote }}
