apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: test
  labels:
    app: server
spec:
  containers:
  - name: server
    image: containous/whoamitcp
    imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: test
  labels:
    app: server
    plop: cool
  annotations:
    maesh.containo.us/traffic-type: tcp
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: server
  selector:
    app: server
