---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: tcp-state-table
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "maesh.chartLabel" . | quote}}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  key: value
