apiVersion: v1
kind: List
metadata:
  name: tracing-services
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: tracing
    namespace: {{ .Release.Namespace }}
    annotations:
      {{- range $key, $val := .Values.service.annotations }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    labels:
      app: {{ .Values.provider }}
      chart: {{ template "tracing.chart" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  spec:
    ports:
      - name: http-query
        port: 80
        protocol: TCP
        targetPort: 16686
    selector:
      app: {{ .Values.provider }}
