name: Build Documentation

on:
  pull_request:

jobs:

  docs:
    name: Doc package
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0

      - name: Package documentation
        run: make docs-package
