name: Build Documentation

on:
  pull_request:

jobs:

  docs:
    name: Doc package
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Package documentation
        run: make docs-package
