---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: maesh-mesh-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "maesh.chartLabel" . | quote}}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: maesh-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "maesh.chartLabel" . | quote}}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maesh-mesh-role
subjects:
  - kind: ServiceAccount
    name: maesh-mesh
    namespace: {{ .Release.Namespace }}
